### ISSUE TITLE
Compatibility 2.2.7 or 2.3

### ISSUE THREAD

**Issue by simonmaass** [elgentos/LargeConfigProducts#27]
any experience/feedback about this?

**Comment by peterjaap** [comment]
I went through the extension file for file and checked the changes in the source file (so the file that is rewritten/pluginized). Here are my results:

`lib/internal/Magento/Framework/View/TemplateEngine/Xhtml/Template.php` last change on Feb 22, 2017 so we're good.

`app/code/Magento/Swatches/Block/Product/Renderer/Configurable.php` 2 recent changes; [this one](https://github.com/magento/magento2/commit/f380abfd74e5238596c0e69da27bfc021c87d23c#diff-f43692cf0626d1c04533bed32b6bdb34) and [this one](https://github.com/magento/magento2/commit/ed7ba4842cdcdde262ffe6c9c4843ef627033a91#diff-f43692cf0626d1c04533bed32b6bdb34), no relevant code for us changed.

`app/code/Magento/ConfigurableProduct/Model/AttributeOptionProvider.php`: last change on May 30, 2017 so we're good.

`app/code/Magento/ConfigurableProduct/Pricing/Price/LowestPriceOptionsProvider.php`: last change on March 3 2018, so that was 2.2.3 so we're good.

`app/code/Magento/Swatches/view/frontend/templates/product/listing/renderer.phtml` has [one change](https://github.com/magento/magento2/commit/d2e66ba244ce394c8eaa2abd2992a9d1d8ded558#diff-f81ffaa60c1bd7810e67f1f63a96e692) from Oct 10th 2018, but since we basically remove everything in that file, we're still good. 

`app/code/Magento/Catalog/view/frontend/templates/product/view/options/wrapper.phtml` - last change on June 6th, 2017 so we're good.

`app/code/Magento/ConfigurableProduct/view/frontend/web/js/configurable.js` - only changes in `_getPrices()` but we don't overwrite that method in our mixin so we're good.

`app/code/Magento/Swatches/view/frontend/web/js/swatch-renderer.js` - [bunch of updates](https://github.com/magento/magento2/commits/2.3-develop/app/code/Magento/Swatches/view/frontend/web/js/swatch-renderer.js) but none related to `init` or `updateBaseImage`, which we are overwriting.

`app/code/Magento/ConfigurableProduct/view/frontend/web/js/configurable-customer-data.js` - no change since September 2, 2016 so we're good.

Which pretty much means that on a superficial file by file level, we're good :tada: 

I've done some preliminary testing on 2.2.7 and everything there seems to be in order, YMMV.

Concerning 2.3.0; since Magento now ships with `Magento_MessageQueue`, for 2.3 we can remove the dependency on `renatocason/magento2-module-mq`. So it will most likely still work OK but we should move the Magento's own MQ implementation over time ([see for more info here](https://devdocs.magento.com/guides/v2.3/extension-dev-guide/message-queues/message-queues.html) - issue #28).

**Comment by simonmaass** [comment]
I can confirm that it works on 2.2.7

**Comment by simonmaass** [comment]
@peterjaap any idea when you will get to that - concerning the queue?

**Comment by peterjaap** [comment]
It seems that it works on 2.2.7 and 2.3.0. Concerning the queue, check #28 for updates (haven't worked on it since).
